{% set name = "cobra" %}
{% set version = "0.26.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cobra-{{ version }}.tar.gz
  sha256: 4c19ed3a1af8376479cc276b83fb3ceb3a373c75353f4d9d41995c6fe81e03ad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - appdirs
    - depinfo =1.7
    - diskcache
    - future
    - httpx
    - importlib_resources
    - numpy >=1.13
    - optlang >=1.5.1
    - pandas >=1.0
    - pydantic >=1.6
    - python >=3.6
    - python-libsbml ==5.19.2
    - rich >=8.0
    - ruamel.yaml >=0.16
    - six
    - swiglpk

test:
  imports:
    - cobra
    - cobra.flux_analysis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://opencobra.github.io/cobrapy
  summary: COBRApy is a package for constraints-based modeling of metabolic networks.
  license: LGPL-2.0-or-later OR GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  description: >
    Constraint-based reconstruction and analysis (COBRA) methods are widely used for genome-scale modeling of metabolic networks in both prokaryotes and eukaryotes. COBRApy is a constraint-based modeling package that is designed to accommodate the biological complexity of the next generation of COBRA models and provides
    access to commonly used COBRA methods, such as flux-balance analysis, flux variability analysis, and gene deletion analyses.
  doc_url: https://cobrapy.readthedocs.io
  dev_url: https://github.com/opencobra/cobrapy

extra:
  recipe-maintainers:
    - cdiener
    - Midnighter
